os: linux
dist: xenial
language: generic
services:
  - docker
env:
  global:
    - DOCKER="goldarte/img-tool:v0.5"
    - TARGET_REPO="https://github.com/Inzhenegri/image-build.git"
    - if [[ -z ${TRAVIS_TAG} ]]; then IMAGE_VERSION="${TRAVIS_COMMIT}}"; else IMAGE_VERSION="${TRAVIS_TAG}"; fi
    - IMAGE_NAME="$(basename -s '.git' ${TARGET_REPO})_${IMAGE_VERSION}.img"
git:
  depth: false
jobs:
  fast_finish: true
  include:
    - stage: Build
      name: "Eyecar modified image build"
      cache:
        directories:
        - imgcache
      before_script:
        - docker pull ${DOCKER}
        - if [ -n "$(ls -A imgcache/*.zip)" ]; then mkdir -p images && cp imgcache/*.zip images; fi
      script:
        - docker run --privileged --rm -v /dev:/dev -v $(pwd):/mnt -e TRAVIS_TAG="${TRAVIS_TAG}" ${DOCKER}
      before_cache:
        - cp images/*.zip imgcache
      before_deploy:
        - git config --local user.name "Arseniyyy"
        - git config --local user.email "arskosh05@mail.ru"
        - sudo chmod -R 777 *
        - cd images && zip ${IMAGE_NAME}.zip ${IMAGE_NAME}
      deploy:
        provider: releases
        token: ${GITHUB_OAUTH_TOKEN}
        file: ${IMAGE_NAME}.zip
        skip_cleanup: true
        on:
          tags: true
        draft: true
        name: ${TRAVIS_TAG}

stages:
 - Build
